name: academybw
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+19

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #STATE
  provider: ^6.0.1

  #STYLE
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  video_player: ^2.4.5
  #flick_video_player: ^0.5.0
  flutter_inappwebview: ^5.4.3+7
  animate_do: ^2.1.0

  #DATA
  shared_preferences: ^2.0.13

  #UTILS
  fluttertoast: ^8.0.7
  table_calendar: ^3.0.6

  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon_app.png"
  adaptive_icon_background: "assets/image/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/videos/
    - i18n/es.json
    - i18n/en.json